# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/LCD_CO1.xdc

# Block Designs: bd/ZYNQ/ZYNQ.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ || ORIG_REF_NAME==ZYNQ} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_processing_system7_0_0/ZYNQ_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_processing_system7_0_0} -quiet] -quiet

# XDC: bd/ZYNQ/ZYNQ_ooc.xdc
