# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PS_PL_REG_CO.xdc

# Block Designs: bd/ZYNQ/ZYNQ.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ || ORIG_REF_NAME==ZYNQ} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_processing_system7_0_0/ZYNQ_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_PS_PL_REG_0_0/ZYNQ_PS_PL_REG_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_PS_PL_REG_0_0 || ORIG_REF_NAME==ZYNQ_PS_PL_REG_0_0} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_auto_pc_0/ZYNQ_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_auto_pc_0 || ORIG_REF_NAME==ZYNQ_auto_pc_0} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_ps7_0_axi_periph_0/ZYNQ_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZYNQ_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_rst_ps7_0_50M_0/ZYNQ_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/ZYNQ/ZYNQ_ooc.xdc
