set_property SRC_FILE_INFO {cfile:H:/xilinx/lly/beep/beep.srcs/constrs_1/new/beep_co.xdc rfile:../../../beep.srcs/constrs_1/new/beep_co.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports beep]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports clk]
