set_property PACKAGE_PIN H18 [get_ports {LED_tri_o[2]}]
set_property PACKAGE_PIN E17 [get_ports {LED_tri_o[1]}]
set_property PACKAGE_PIN K19 [get_ports {LED_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[0]}]