# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_processing_system7_0_0/ZYNQ_processing_system7_0_0.xci
# IP: The module: 'ZYNQ_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_processing_system7_0_0/ZYNQ_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: H:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_processing_system7_0_0/ZYNQ_processing_system7_0_0.xci
# IP: The module: 'ZYNQ_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_processing_system7_0_0/ZYNQ_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
