# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/HDMI_color.xdc

# Block Designs: bd/clk_wiz_0/clk_wiz_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: bd/clk_wiz_0/ip/clk_wiz_0_clk_wiz_0_0/clk_wiz_0_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0_clk_wiz_0_0 || ORIG_REF_NAME==clk_wiz_0_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/clk_wiz_0/clk_wiz_0_ooc.xdc
