set_property PACKAGE_PIN R18 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN N17 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN P20 [get_ports SPI_0_0_io0_io]
set_property PACKAGE_PIN R19 [get_ports SPI_0_0_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_sck_io]

set_property PACKAGE_PIN N17 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN T20 [get_ports SPI_0_0_ss_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_ss_io]
