# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/ZYNQ_axi_smc_0.xci
# IP: The module: 'ZYNQ_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/bd_83df.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_0/bd_83df_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_1/bd_83df_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_2/bd_83df_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_3/bd_83df_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_4/bd_83df_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_5/bd_83df_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_6/bd_83df_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_7/bd_83df_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_8/bd_83df_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_9/bd_83df_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_10/bd_83df_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_11/bd_83df_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_12/bd_83df_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_1/bd_83df_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_1/bd_83df_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_5/bd_83df_s00a2s_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_6/bd_83df_sarn_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_7/bd_83df_srn_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_8/bd_83df_sawn_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_9/bd_83df_swn_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_10/bd_83df_sbn_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_11/bd_83df_m00s2a_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: H:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/ZYNQ_axi_smc_0.xci
# IP: The module: 'ZYNQ_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/bd_83df.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_0/bd_83df_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_1/bd_83df_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_2/bd_83df_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_3/bd_83df_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_4/bd_83df_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_5/bd_83df_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_6/bd_83df_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_7/bd_83df_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_8/bd_83df_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_9/bd_83df_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_10/bd_83df_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_11/bd_83df_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_12/bd_83df_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_1/bd_83df_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_1/bd_83df_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_5/bd_83df_s00a2s_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_6/bd_83df_sarn_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_7/bd_83df_srn_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_8/bd_83df_sawn_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_9/bd_83df_swn_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_10/bd_83df_sbn_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/bd_0/ip/ip_11/bd_83df_m00s2a_0_ooc.xdc

# XDC: h:/ZYNQ/lly_study_work/DDR3_1bit/DDR3_bit/DDR3_bit.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
