set_property SRC_FILE_INFO {cfile:H:/Xilinx2019.1/lly/201901LED_PS_TEST/201901LED_PS_TEST.srcs/constrs_1/new/LED_CO.xdc rfile:../../../201901LED_PS_TEST.srcs/constrs_1/new/LED_CO.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports LED_tri_o[0]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports LED_tri_o[1]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports LED_tri_o[2]]
