# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/ZYNQ/lly_study_work/VDMA_READ/VGA_HDMI/VGA_HDMI.srcs/sources_1/bd/VTC/ip/VTC_processing_system7_0_0/VTC_processing_system7_0_0.xci
# IP: The module: 'VTC_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ZYNQ/lly_study_work/VDMA_READ/VGA_HDMI/VGA_HDMI.srcs/sources_1/bd/VTC/ip/VTC_processing_system7_0_0/VTC_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'VTC_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: H:/ZYNQ/lly_study_work/VDMA_READ/VGA_HDMI/VGA_HDMI.srcs/sources_1/bd/VTC/ip/VTC_processing_system7_0_0/VTC_processing_system7_0_0.xci
# IP: The module: 'VTC_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ZYNQ/lly_study_work/VDMA_READ/VGA_HDMI/VGA_HDMI.srcs/sources_1/bd/VTC/ip/VTC_processing_system7_0_0/VTC_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'VTC_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
