# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/LED_CO.xdc

# Block Designs: bd/ZYNQ_CORE/ZYNQ_CORE.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE || ORIG_REF_NAME==ZYNQ_CORE} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_processing_system7_0_0/ZYNQ_CORE_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_CORE_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_gpio_0_0/ZYNQ_CORE_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_gpio_0_0 || ORIG_REF_NAME==ZYNQ_CORE_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_pc_0/ZYNQ_CORE_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_pc_0 || ORIG_REF_NAME==ZYNQ_CORE_auto_pc_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_ps7_0_axi_periph_0/ZYNQ_CORE_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZYNQ_CORE_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_rst_ps7_0_50M_0/ZYNQ_CORE_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZYNQ_CORE_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/ZYNQ_CORE/ZYNQ_CORE_ooc.xdc
